name: Generate Snake

on:
  # Se ejecuta autom치ticamente cada 24 horas
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite ejecutarlo manualmente desde la pesta침a Actions
  workflow_dispatch:
  
  # Se ejecuta al hacer push a la rama main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Bajar el c칩digo del repositorio
      - uses: actions/checkout@v3

      # 2. Generar la serpiente
      - name: Generar la serpiente de contribuciones
        uses: Platane/snk@v3
        with:
          # Nombre de usuario (autom치tico)
          github_user_name: ${{ github.repository_owner }}
          
          # Archivos a generar
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      # 3. Publicar el archivo generado en una rama separada
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
